#!/usr/bin/env node
// Generates tokens.css (CSS custom properties, light + dark) and tailwind-theme.css
// (Tailwind v4 @theme mapping) from tokens.json + tokens.dark.json.
// Usage: node build-tokens.mjs [outDir]   (default: this folder)
// Edit the JSON, never the generated CSS.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(process.argv[2] ?? here);
const light = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const dark = JSON.parse(readFileSync(join(here, "tokens.dark.json"), "utf8"));

// Runtime variables (theme-switchable) use short prefixes: --c-* colours, --sh-* shadows.
// Tailwind theme variables (--color-*, --shadow-*) point at them, so names never self-reference.
const colorVars = (t) => Object.entries(t.color).map(([k, v]) => `  --c-${k}: ${v};`);
const shadowVars = (t) => Object.entries(t.shadow).map(([k, v]) => `  --sh-${k}: ${v};`);
const block = (sel, t, scheme) =>
  `${sel} {\n  color-scheme: ${scheme};\n${[...colorVars(t), ...shadowVars(t)].join("\n")}\n}`;

const motion = Object.entries(light.motion).map(([k, v]) => `  --motion-${k}: ${v};`);
const layout = Object.entries(light.layout).filter(([, v]) => typeof v === "number")
  .map(([k, v]) => `  --layout-${k}: ${v}px;`);
const z = Object.entries(light.z).map(([k, v]) => `  --z-${k}: ${v};`);

const tokensCss = `/* GENERATED by replica/design/build-tokens.mjs from tokens.json + tokens.dark.json. Do not edit. */
:root {\n${[...motion, ...layout, ...z].join("\n")}\n}

${block(":root", light, "light")}

@media (prefers-color-scheme: dark) {
${block(':root:not([data-theme="light"])', dark, "dark").replace(/^/gm, "  ")}
}

${block(':root[data-theme="dark"]', dark, "dark")}
`;

// Tailwind v4 theme. Colours and shadows switch with the theme, so they map to runtime vars
// (@theme inline). Type, radius, fonts, spacing and breakpoints are static (@theme).
const inline = [];
for (const k of Object.keys(light.color)) inline.push(`  --color-${k}: var(--c-${k});`);
for (const k of Object.keys(light.shadow)) inline.push(`  --shadow-${k}: var(--sh-${k});`);
inline.push(`  --ease-out: var(--motion-ease);`);

const stat = [`  --font-sans: ${light.font.sans};`, `  --font-mono: ${light.font.mono};`, `  --spacing: 4px;`];
for (const [k, v] of Object.entries(light.type)) {
  stat.push(`  --text-${k}: ${v.size / 16}rem;`, `  --text-${k}--line-height: ${v.line / 16}rem;`,
            `  --text-${k}--font-weight: ${v.weight};`);
}
for (const [k, v] of Object.entries(light.radius)) stat.push(`  --radius-${k}: ${v === 999 ? "9999px" : v / 16 + "rem"};`);
for (const [k, v] of Object.entries(light.layout.breakpoints)) stat.push(`  --breakpoint-${k}: ${v / 16}rem;`);

const twCss = `/* GENERATED by replica/design/build-tokens.mjs. Do not edit. Import after "tailwindcss". */
@theme {
  --color-*: initial;
  --text-*: initial;
  --radius-*: initial;
  --shadow-*: initial;
${stat.join("\n")}
}

@theme inline {
${inline.join("\n")}
}

/* text-muted reads better than text-text-muted; text-fg is the default text colour. */
@utility text-muted { color: var(--c-text-muted); }
@utility text-fg { color: var(--c-text); }
`;

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "tokens.css"), tokensCss);
writeFileSync(join(out, "tailwind-theme.css"), twCss);
console.log(`wrote ${join(out, "tokens.css")} and ${join(out, "tailwind-theme.css")}`);
